export const ValidationError = {
  VALIDATION_FAILD: "VALIDATION_FAILD",
  REQUIRED_FAILD_MISSING: "REQUIRED_FAILD_MISSING",
  INVALID_FORMAT: "INVALID_FORMAT",
  OUT_OF_RANGE: "OUT_OF_RANGE",
  INVALID_DATE: "INVALID_DATE",
  INVALID_TAGS: "INVALID_TAGS"
}

export const AuthError = {
  UNAUTHORIZED: "UNAUTHORIZED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  FORBIDDEN: "FORBIDDEN",
  ACCOUNT_DISABLED: "ACCOUNT_DISABLED",
  SESSION_EXPIRED: "SESSION_EXPIRED"
}

export const DuplicateError = {
  DUPLICATE_CATEGORY_NAME: "DUPLICATE_CATEGORY_NAME",
  DUPLICATE_LEDGER_NAME: "DUPLICATE_LEDGER_NAME",
  DUPLICATE_TAG_NAME: "DUPLICATE_TAG_NAME",
  DUPLICATE_EMAIL: "DUPLICATE_EMAIL"
}

export const BaseError = {
  USER_NOT_FOUND: "USER_NOT_FOUND"
}

export function throwError(e) {
  throw new GraphQLError("Internal server error", {
    extensions: { code: "INTERNAL_SERVER_ERROR" }
  });
}